description: MAPO

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: tabert_electra_contrastive_concat_quarter_ep3
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_electra_contrastive_concat_quarter_ep3
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_contrastive_concat_quarter_ep5_fast/pytorch_model_epoch02.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_roberta_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_roberta_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_roberta_ep5/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_2row_ep1
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_2row_ep1
    /mnt/root/TaBERT/data/runs/vanilla_tabert_2row_ep5/pytorch_model_epoch00.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_2row_ep3
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_2row_ep3
    /mnt/root/TaBERT/data/runs/vanilla_tabert_2row_ep5/pytorch_model_epoch02.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_electra_2row_ep1
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_electra_2row_ep1
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_2row_ep5/pytorch_model_epoch00.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_electra_2row_ep3
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_electra_2row_ep3
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_2row_ep5/pytorch_model_epoch02.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskvalue_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskvalue_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_ep5/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskvalue_samplevalue_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskvalue_samplevalue_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_ep5/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskvalue_samplevalue_maskusedcolumn_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskvalue_samplevalue_maskusedcolumn_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_maskusedcolumn_ep5/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_ep20
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_ep20
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep20/pytorch_model_epoch19.bin
    /mnt/root/MAPO
- name: tabert_totto_maskseparate_ep10
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_ep10
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep10/pytorch_model_epoch09.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep10/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskwhole_ep10
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskwhole_ep10
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskwhole_ep10/pytorch_model_epoch09.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskwhole_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskwhole_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskwhole_ep10/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_nsp_ep10
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_nsp_ep10
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_nsp_ep10/pytorch_model_epoch09.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_nsp_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_nsp_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_nsp_ep10/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_contrastive_concat_ep10
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_contrastive_concat_ep10
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_contrastive_concat_ep10/pytorch_model_epoch09.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
- name: tabert_totto_maskseparate_contrastive_concat_ep5
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_totto_maskseparate_contrastive_concat_ep5
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_contrastive_concat_ep10/pytorch_model_epoch04.bin
    /vc_data/users/t-zhjiang/exp/pytorch_neural_symbolic_machines
