description: MAPO

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: MAPO
  sku: G4
  sku_count: 1
  command:
  - ./exp.sh tabert_roberta_contrastive_ep5 /mnt/root/TaBERT/data/runs/vanilla_tabert_roberta_contrastive_ep5/pytorch_model_epoch04.bin /mnt/root/MAPO
